defaults:
  - _self_

# Model choices: 
#  ShuffleNet_V2_X0_5
#  MobileNet_V3_Large
#  MobileNet_V3_Small
#  VisionIKModel
model: 
  name: "MobileNet_V3_Small" 
  train_joints: # Options: ["waist", "shoulder", "elbow", "forearm_roll", "wrist_angle", "wrist_rotate"]
    - "waist"
    - "shoulder"
  
# Training configuration
trainer:
  batch_size: 40
  learning_rate: 1e-4
  epochs: 100000
  num_workers: 8
  project_name: "cobot/vision-ik"
  model_checkpoint_path: "vision_ik_model.pth"
  checkpoint_interval: 100000  # Save checkpoint. Takes that much to converge anyways
  resume_checkpoint: null  # Path to checkpoint file to resume from

# Dataset configuration
dataset:
  dataset_dir: "Absolute path to dataset directory"
  save_plots: false
  stat_percentile_range: [1, 99]
  augmentations:
    apply: true
    ColorJitter:
      brightness: 0.15
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
      p: 0.3
    RandomPerspective: 
      distortion_scale: 0.05
      p: 0.0
    ElasticTransform: 
      alpha: 50.0
      sigma: 7.0
      p: 0.0
    RandomResizedCrop:
      crop_scale: 0.999
      scale: [0.999, 1.0]
      ratio: [0.999, 1.01]
      p: 0.0
    JPEGCompression:
      quality_range: [80, 95]
      p: 0.5

# Neptune configuration
neptune:
  api_token: "<Neptune API Token>"
